version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Монтируем на хосте файл ./data/app.db
    # в контейнере он будет доступен как /app/src/app.db
    volumes:
      - ./data/app.db:/app/src/app.db