name: Build and Push Docker Image (Single Service)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp tag
        run: echo "TAG_DATE=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .           # Папка, где лежит Dockerfile
          file: ./Dockerfile   # Укажи путь, если он отличается
          push: true
          tags: albeliakov/langs-of-russia-img:latest, albeliakov/langs-of-russia-img:${{ env.TAG_DATE }}
